name: Enterprise Terraform Deploy

on:
  push:
    branches:
      - main

permissions:
  id-token: write # OIDC認証に必須
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Get OIDC Token and Check Claim
        uses: actions/github-script@v7
        with:
          script: |
            const token = await core.getIDToken('sts.amazonaws.com');
            console.log("--- OIDC TOKEN JWT (Payload part) ---");
            const payload = JSON.parse(Buffer.from(token.split('.')[1], 'base64').toString());
            console.log(JSON.stringify(payload, null, 2));
            
      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::950177941522:role/github-actions-s3-role
          aws-region: us-east-1
          audience: sts.amazonaws.com

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -input=false

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve -input=false
